[package]
name = "loopscope"
version = "0.1.0"
authors = ["Mec-iS <tunedconsulting@gmail.com>"]
edition = "2018"

[dependencies]
ears = "*"
rand = "*"
itertools = "*"
text_io = "*"

[profile.release]
debug = true